### ISSUE TITLE
Proposed n2cms nuget package organization

### ISSUE THREAD

**Issue by bherila** [n2cms/n2cms#271]
I think we should rename the N2CMS package to N2CMS.Core (and also remove the dependency on N2CMS.Management). Then we can create a series of N2CMS installation packages: 
- N2CMS-Webforms
- N2CMS-Dinamico
- N2CMS-MvcTemplates

With each of these packages you would get: 
- N2CMS.Core
- N2CMS.Management.Zip or NoZip (I like NoZip but we can take a vote :-) )
- The relevant template pack (e.g. N2CMS.Dinamico)

![image](https://f.cloud.github.com/assets/1422004/905526/3e7c78b4-fc32-11e2-83d4-ff2f65cb8dfe.png)

This way you could do something like N2CMS-Dinamico to get the recommended set of stuff. Or, you could just compose the individual packages if you wanted a slimmer installation.

**Comment by bussemac** [comment]
I have a couple of more complex projects that utilize a separate ViewModel layer outside the main web project. When trying to define page types here that reference N2, currently I have to install N2.Management into that project, which results in a lot of extra files I don't need. The ideal solution for me would be if there was a separate N2.Core that does not install/depend on the N2.zip, but just references the DLL files so I can create my own page types that descend from ContentItem, etc. without needing the N2.zip, etc.
