### ISSUE TITLE
_escaped_fragment_ get's rewrited before url rewrite module can process it.

### ISSUE THREAD

**Issue by Tazer** [n2cms/n2cms#572]
Hello,

We are using n2cms for a page that have some SPA features , 

So we want to be able to use a snapshot server , using URL Rewrite , IF url contains _escaped_fragment_ , do an url rewrite. The problem is that N2 seems to rewrite this before the URL Module get's the request. Do you have any ideas how I could solve this problem ?

**Comment by samfromlv** [comment]
Hello,

We are having problems because of this fix. ASP.NET MVC controller action with _escaped_fragment_ param never called. ContentRoute block all requests to application controllers.

Test action:
`public ActionResult Test(string _escaped_fragment_)
        {
            return Content("OK");
        }`

Routes configuration:
```
routes.Add(new ContentRoute(engine));
routes.MapRoute(
                name: "Default",
                url: "{controller}/{action}/{id}",
                defaults: new { controller = "CMSStartPage", action = "Index", id = UrlParameter.Optional });
```

Our workaround:
```
public class N2CustomContentRoute:ContentRoute
    {
        public N2CustomContentRoute(IEngine engine)
            : base(engine){}

        public override System.Web.Routing.RouteData GetRouteData(HttpContextBase httpContext)
        {
			if (httpContext.Request.QueryString["_escaped_fragment_"] != null)
			{
				return null;
			}

            return base.GetRouteData(httpContext);
		}
    }
```

**Comment by bherila** [comment]
The issue is probably with your web.config. Make sure this setting is `false` because otherwise after URL Rewriting rewrites the URL, the .NET application might re-route it back.

```
  <system.webServer>
    <modules runAllManagedModulesForAllRequests="true">
```
