### ISSUE TITLE
[Compat] Management interface problem in IE9

### ISSUE THREAD

**Issue by andpoulsen** [n2cms/n2cms#602]
In IE9 I get "Object doesn't support property or method 'cookie' at the line 

```
isOpen: function () {
    return $.cookie("sc_open") == "true";
```

in parts.js.

This occured both in version 2.6.2.2, 2.6.3 and 2.6.3.8.

When I do `$.cookie` in the console I get `undefined`. If I reload the page several time, then the error goes away every now and then, but comes back, when I reload. 
The sympoms are that the sliding curtain doesn't appear and when I try to expand pages in the tree-view to view sub-pages, then the entire interface reloads (without expanding the page!).

The error does not occur in IE11.

**Comment by DejanMilicic** [comment]
@andpoulsen I suppose this is not an issue anymore? IE9, to be precise

**Comment by andpoulsen** [comment]
It's probably not fixed, but it is not "an issue" anymore ;)
You can close if you like
