### ISSUE TITLE
Updating to 2.6.3.8 causes a System.Configuration.ConfigurationErrorsException exception

### ISSUE THREAD

**Issue by FloatLeft** [n2cms/n2cms#616]
Just used NuGet to upgrade to 2.6.3.8 from 2.6.3.2 and now get the following exception: 

An exception of type 'System.Configuration.ConfigurationErrorsException' occurred in System.Configuration.dll but was not handled in user code 

Additional information: Unrecognized attribute 'ckEditorPath'. Note that attribute names are case-sensitive.

If I remove the attribute from web.config, the content editing boxes disappear in the management window.

Renaming the key from ckEditorPath to ckEditorJsPath has no effect.

**Comment by FloatLeft** [comment]
any takers?

**Comment by libardo** [comment]
Try <resources ckEditorJsPath="/hello"/>

Sorry about the breaking change.

**Comment by FloatLeft** [comment]
The version is 2.6.3.8

ckeditor.js seems to be missing from the n2.zip file
