### ISSUE TITLE
Exception in Redirect.cshtml template

### ISSUE THREAD

**Issue by lisamariet** [n2cms/n2cms#619]
There is an else missing for if permanent redirect or not. If "Permanent redirect" is check on page then exception occurs becuase Redirect is called twice. 

Exception type: HttpException
Exception message: Server cannot set status after HTTP headers have been sent.

This fixes the issue: 
      if (perm)
        {
            Response.RedirectPermanent(url);
        }
        else
        {
            Response.Redirect(url);
        }

**Comment by DejanMilicic** [comment]
Examining code, I can see this is not an issue anymore. If you still have problems, please reopen this issue
