### ISSUE TITLE
What's the roadmap/plan for n2cms ?

### ISSUE THREAD

**Issue by Tazer** [n2cms/n2cms#624]
Hey! 

Would be nice to know if there is a roadmap/plan for n2cms. As last commit was "7 Dec 2014" ? Just a status update, If someone going to push it forward ? or will the project be left as is ?

**Comment by bherila** [comment]
One of the lead developers had a baby so I think he's been pretty busy lately. We are focused on fixing bugs ourselves and keeping issues answered on the community (usually within a few days). We will take code contributions but top-down new features are a lower priority right now due to time constraints.

**Comment by Tazer** [comment]
Understand.

Way I'm asking is cause ASP.NET 5 is starting to get som traction. So is there any plans to make n2cms work with ASP.NET 5 (vnext) and the new core ?

**Comment by DejanMilicic** [comment]
N2CMS is active project with level of activity varying over time, but it is far from being abandoned or not active. So far we tracked progress in ASP.NET development so I am sure this will be the case with next version too

**Comment by dazinator** [comment]
Any more news on Asp.net Core / Mvc 6?

**Comment by bherila** [comment]
I don't know of a particular reason why we need that... but we'd definitely work with anyone who wanted to build that out and submit a PR. There are still some dependencies on web forms, so this is likely a larger undertaking.

**Comment by bherila** [comment]
Now that I am using N2CMS again actively in my projects, I expect we'll be able to add some new features and fix bugs too. So yay for that 👍
