### ISSUE TITLE
Write Manually not working when add new a news page

### ISSUE THREAD

**Issue by hungnguyenphuoc** [n2cms/n2cms#625]
Hi @bherila  

When adding new a news page, if check the Write Manually and write some text in Summary and save. The summary text was not saved.

Please show me the code in the framework or the script in this follow to check it out.

Thanks,

**Comment by bherila** [comment]
Editing the summary: 
https://github.com/n2cms/n2cms/blob/master/src/Framework/N2/Details/EditableSummaryAttribute.cs

Persisting the attribute: 
https://github.com/n2cms/n2cms/blob/456f5b817063f62c796a536acf6a4417c5a108e1/src/Framework/N2/Edit/Workflow/Commands/SaveCommand.cs

Also look at `IPersister` for the logic that saves the changes to the database. You can set a breakpoint on Persister.SaveChanges. 

What storage engine are you using?

**Comment by hungnguyenphuoc** [comment]
Hi @bherila 

I've tried to debug two follow at both adding and editing. The main difference of them can described by the attachments.

The base type of the item not are the same. Please provide the solution here.

![update](https://cloud.githubusercontent.com/assets/10041656/6487239/9b0b87a6-c255-11e4-948f-fbda8ac60fbc.PNG)
![create](https://cloud.githubusercontent.com/assets/10041656/6487240/9b0dc994-c255-11e4-99ba-066d45fc0b89.PNG)

**Comment by hungnguyenphuoc** [comment]
The yellow painted is at editing

**Comment by hungnguyenphuoc** [comment]
![debug](https://cloud.githubusercontent.com/assets/10041656/6488101/bf7aace8-c25a-11e4-8530-d3cf4cbe3dcc.PNG)

i saw the text of the summary in the AddedEditors is empty in the adding

**Comment by libardo** [comment]
It turned out to be related to textbox readonly and security changes in asp.net

**Comment by hungnguyenphuoc** [comment]
Thanks so much.

**Comment by bherila** [comment]
Thanks @libardo :+1:
