### ISSUE TITLE
Can't upload more than a few files simultaneously

### ISSUE THREAD

**Issue by bussemac** [n2cms/n2cms#629]
version 2.6.3.8
If you go to the upload folder and drag files onto it, no more than 2 will be taken. If you use the browse button and select files, you might get as many as 4 at once, but I've never been able to get more.

It's not MaxRequestLength problem; I'm using 5 files totaling 168KB and have a MaxRequestLength over 20 MB.

**Comment by SntsDev** [comment]
I have the same problem in many sites, both in production and development. The browser console shows an error 500 in UploadFile.ashx.

I already tried many things:
* Update jQUery-upload-file to latest version. 
* Trace the application to see the error. They don't appear, only the 304 or 200 responses.
* I can see that the ticket is ok (and the same) both in sucessed and failed tries, as well as other values of the post body. So I don't think it's a matter of authentication.
* VS cannot intercept the error neither, but it does fail and Firebug console shows the 500.


![captura de pantalla 2015-04-09 a las 9 39 14](https://cloud.githubusercontent.com/assets/4103411/7062434/76bce9bc-de9d-11e4-8a64-8072d4dd6a73.png)

Thanks
