### ISSUE TITLE
Is "RawHtml" part is remove from StartPage ?  - N2CMS Version 2.6.3.8 

### ISSUE THREAD

**Issue by kunallondhe** [n2cms/n2cms#638]
N2CMS Version 2.4 - Start Page contains part RawHtml, Now the latest version is not showing this part in the List. Please refer following screen shot.

Has this part been removed from list? Is there any other way to used this part?

![image](https://cloud.githubusercontent.com/assets/108206/7566122/c5726454-f812-11e4-81a6-7468a9aa01e0.png)

**Comment by bherila** [comment]
I believe it's refactored into http://www.nuget.org/packages/N2CMS.ReusableParts/

**Comment by kunallondhe** [comment]
Thanks.. It's Working :+1:
