### ISSUE TITLE
Class LuceneIndexer - Method CreateLuceneDocument() is Missing in - N2CMS 2.6

### ISSUE THREAD

**Issue by kunallondhe** [n2cms/n2cms#641]
In Version  2.4, I have method CreateLuceneDocument(N2.ContentItem) but in version 2.6  the method is missing. 

Code :
LuceneIndexer.Setup(x => x.CreateLuceneDocument(ContentItem)).Returns(new Document());

I tried to find the method. but I did not get it.
 
and above code giving me below error

Error	150	'N2.Persistence.Search.LuceneIndexer' does not contain a definition for 'CreateLuceneDocument' and no extension method 'CreateLuceneDocument' accepting a first argument of type 'N2.Persistence.Search.LuceneIndexer' could be found (are you missing a using directive or an assembly reference?)

**Comment by libardo** [comment]
That method has moved to another class: TextExtractor
