### ISSUE TITLE
NHTransaction giving following error  Version 2.6

### ISSUE THREAD

**Issue by kunallondhe** [n2cms/n2cms#642]
I am getting following error in my log file, if anyone knows any information then please let me known.

ERROR : 2015-05-13 19:24:16.2023 - WARN w3wp.exe (www.local.main WIN-QKA0) 2015-05-13 18:24:16.201 [5] NHTransaction: Not commiting 29264488, isOriginator:False, wasCommitted:False, wasRolledBack:False

**Comment by libardo** [comment]
This warning indicates that a transaction was about to be committed twice, or that a transaction within another transaction was about to be committed. N2 implements code to prevent this. If this cause problems or if you find a way to reproduce this please re-open with more information. Thanks!
