### ISSUE TITLE
How remove part from Organizer Part List - Version 2.6

### ISSUE THREAD

**Issue by kunallondhe** [n2cms/n2cms#644]
Hi 
I want the remove the part from the Organizer Part list and this part is the member of N2.ReusablePart namespace.any idea?

How to used "Setting Container" and "Resource Container" ?

**Comment by libardo** [comment]
* Make sure to you don't have any of these parts (also check trash)
* Browse to /N2/installation/diagnose.aspx
* Expand Definitions
* Locate the part you want to remove
* In the type column, the gray text is the part's name, copy this for the next step
* In web.config remove the part's definition:
```xml
	<n2>
		<engine>
			<definitions>
				<remove name="NAMEOFPARTTOREMOVE"/>
```
