### ISSUE TITLE
Management 2.7.1 icon issues

### ISSUE THREAD

**Issue by stuartmanners** [n2cms/n2cms#645]
Since migrating to 2.7.1 some of the icons have disappeared from the top navigation. The CSS class names needs to be updated.

![n2 management 2015-05-18 17-06-36](https://cloud.githubusercontent.com/assets/12499353/7684761/99bff6f0-fd80-11e4-861e-02a3b2141856.png)

**Comment by stuartmanners** [comment]
The necessary updates were made to /src/Mvc/MvcTemplates/N2/App/Partials/ContentVersions.html etc but it doesn't look like these were included in the v2.7.1 update on NuGet.

**Comment by libardo** [comment]
I can't reproduce this with ZIP or NOZIP management packages. Are you sure this isn't some local cache? Is it possible some artifacts remains from the previous version?
