### ISSUE TITLE
Can't rename upload folder

### ISSUE THREAD

**Issue by hudo** [n2cms/n2cms#646]
When tried to rename upload folder I got "Illegal characters in path." exception.

To reproduce: just open Upload item in existing or new N2 installation (admin UI), enter edit mode of Upload item, change to something new, try save. 

I traced problem to Save method of N2.Edit.FileSystem.Items.Directory.cs, where in this line 107:

    var parentUrl = ParentDirectory != null ? ParentDirectory.LocalUrl : Parent.Url;

resolves something like "/N2/Myself/Root.aspx?n2page=1" instead of just "/" (ParentDir is null), so it fails on System.IO.Path.CheckInvalidPathChars.

**Comment by DejanMilicic** [comment]
[ArgumentException: Illegal characters in path.]
   System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional) +148
   System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList) +156
   System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList) +38
   System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String path) +88
   System.Web.Hosting.HostingEnvironment.MapPath(VirtualPath virtualPath) +128
   N2.Edit.FileSystem.MappedFileSystem.MoveDirectory(String fromVirtualPath, String destinationVirtualPath) +55
   N2.Edit.FileSystem.Items.Directory.Save() +294
   N2.Edit.Workflow.Commands.CompositeCommand.Process(CommandContext context) +67
   N2.Edit.Workflow.CommandDispatcher.Execute(CommandBase`1 command, CommandContext context) +785
   N2.Edit.Edit.OnPublishCommand(Object sender, CommandEventArgs e) +61
   System.Web.UI.WebControls.LinkButton.OnCommand(CommandEventArgs e) +173
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +3554

**Comment by libardo** [comment]
The default upload folder is connected to a location on disk, to change or add use config:

```xml
  <n2 xmlns="http://n2cms.com/schemas/configuration/v3">
			<uploadFolders>
				<clear/>
				<add path="~/downloads" title="Downloads"></add>
			</uploadFolders>
    </edit>
  </n2>
```

**Comment by hudo** [comment]
Works like a charm, thanks!
