### ISSUE TITLE
Unable to install nuget package N2CMS.Dinamico on Visual Studio 2015 RC

### ISSUE THREAD

**Issue by sveinfid** [n2cms/n2cms#649]
I am unable to install the N2CMS.Dinamico 2.7.2 NuGet package on Visual Studio 2015 RC.

NuGet hangs on the message: Attempting to gather dependencies information for package 'n2cms.dinamico.2.7.2' with respect to project targeting '.NETFramework, Version=v4.5.2' and in the end stops with an Out Of Memory error

Steps to reproduce:
* Fresh install of Visual Studio 2015 RC Enterprise (5/27/2015 release date). I used the VM image in Azure on a D2 Virtual Machine.
* New ASP.NET Web Application project using .NET 4.5.2. (The same goes for .NET 4.6)
* ASP.NET 4.6 MVC template
* Install-Package N2CMS.Dinamico

**Comment by sveinfid** [comment]
When I receive the Out Of Memory error in the Package Manager Console, Visual Studio is using about 2.5 GB of memory.

**Comment by bherila** [comment]
This sounds like a problem that should be reported to the Nuget and/or Visual Studio (at Microsoft) team.

**Comment by sveinfid** [comment]
I'm seeing another error on Visual Studio 2015 RTM when installing NuGet package N2CMS.Dinamico: "Could not find file 'C:\...\Google%2B1.cshtml'."

Seems there is some issue with the plus sign in the filename.


Details:
```
Package Manager Console Host Version 3.0.0.0

Type 'get-help NuGet' to see all available NuGet commands.

PM> install-package n2cms.dinamico

(...)

install-package : Could not find file 'C:\Users\<username>\.nuget\packages\N2CMS.Dinamico\2.7.5\Content\Dinamico\Themes\Default
\Views\Shared\TokenTemplates\Google%2B1.cshtml'.
At line:1 char:1
+ install-package n2cms.dinamico
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
PM> 
```

**Comment by libardo** [comment]
Fixed

**Comment by sveinfid** [comment]
Actually, updating NuGet from version 3.0.0.0 to version 3.2.0.10516 did the trick. Now N2CMS.Dinamico installs just fine.

To compile the project, however, nuget package N2CMS.Management is required as well.

Please close the issue.
