### ISSUE TITLE
Multiple sites with output cache enabled causes wrong content to be displayed for start page.

### ISSUE THREAD

**Issue by simon-d** [n2cms/n2cms#657]
Running version 2.7.3 of N2, I have an instance running with mutlipleSites set to true and the output cache enabled.

Two of the sites run under sub-domains of the primary site. By navigating to one of the sub domain sites, and then navigating to the second sub site, the content displayed is the content from the first sub domain site. Refreshing the page eventually displays the correct content, which lead me to believing the cache may be the cause.

I was able to setup an environment locally to reproduce the issue, adding two sub domains to localhost  (alpha.localhost & beta.localhost) in my windows hosts file. I configured Visual Studio to run the site in IIS on domain localhost, and configured the domain settings for the other two sites to use the local sub domains.

After disabling the output cache, switching back and forth between the two sub domain sites never displayed the incorrect content again. For now I've disabled the output cache in production to avoid the incorrect content being displayed to users.

**Comment by DejanMilicic** [comment]
@simon-d Can you please state precisely configuration you used for turning on/off output cache

**Comment by simon-d** [comment]
My host configuration in N2 section looked like below. I ended up commenting out the output cache line in production to disable the cache.

```xml
<host rootID="1" startPageID="2" multipleSites="true">
      <!-- output cache caches the rendered page and
           is invalidated when a page is published -->
      <outputCache enabled="true" duration="10"/>
      <web extension="" pageQueryKey="n2page"/>
</host>

**Comment by libardo** [comment]
We recently changed the default when publishing to only invalidate the current page. 
Configuring
			<outputCache invalidateOnChangesTo="All"/>
should restore the previous invalidation strategy. Configuring "Site" might work for you if you want to invalidate less often:
			<outputCache invalidateOnChangesTo="Site"/>
