### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by natiki** [n2cms/n2cms#669]
Hi,

Just wondering if things are still being worked on? There have been no releases in 2015 and very little activity? I am looking into n2cms for an upcoming project as it appears it is exactly what I need, so I am curious?

**Comment by bherila** [comment]
I haven't been commissioned for anything that demanded new feature work on N2CMS, however we are still alive and well. The project is stable and I'm using it on several websites.

**Comment by natiki** [comment]
Hi,

Great to hear the project is alive and well. While I was browsing the website I found a few broken links:

- http://n2cms.com/wiki.aspx
- Download link on nscms.com still directs to CodePlex

**Comment by bherila** [comment]
Oh yeah, the n2cms.com website is way out of date. Sorry about that. Best documentation is currently the Confluence wiki: https://n2cmsdocs.atlassian.net/wiki/display/N2CMS/n2cms+Home

**Comment by natiki** [comment]
Cool, thanks I will browse for info there.
