### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by redbarns** [n2cms/n2cms#671]
Is there a responsive theme or bootstrap for n2cms?  I downloaded the latest version and I see in the admin I can view what the page would look like on different devices, but I don't see a way to make a mobile friendly interface or control for the page.
Thanks

**Comment by bherila** [comment]
There are some responsive parts included in the Dinamico theme package. N2CMS doesn't prevent you from building a responsive site. The management UI is not fully mobile-ready but @libardo  has made some improvements towards tablet support by improving the drag-n-drop parts editor.
