### ISSUE TITLE
Save & publish in future window freeze.

### ISSUE THREAD

**Issue by legomyego** [n2cms/n2cms#672]
N2 version: 2.6.3.8
1. Press 'Edit' on Content page/Banner
2. Press arrow between 'Save and publish' button on the bottom. http://prntscr.com/8753jw and choose  'Save and publish in the future'
3. Windows opens - http://prntscr.com/8753rx
4. 'Cancel' button and closing cross (on the right top corner) doesn't work, if you want to close window without choosing any time, you should refresh page. 'OK' button works properly.

**Comment by bherila** [comment]
What browser/version?
