### ISSUE TITLE
Issues with EditableNumber

### ISSUE THREAD

**Issue by laurachan** [n2cms/n2cms#673]
1. If an EditableNumber detail is not required, and you blank out the text box, saving the page or part results in a FormatException: Input string was not in a correct format. 
2. Is there any way to stop N2CMS from pre-filling the text boxes with 0 if you don't specify a different default value? I have a site setting where 0 would not be a valid value but there isn't really a non-zero value that would be reasonable to hardcode as default.
3. There doesn't seem to be a Dinamico dynamic registration method for adding a number detail to a page or part template. It'd be nice to be able to do something like `Content.Define(re => { re.Number("TestNumber"); });` instead of manually creating an EditableNumberAttribute and using re.Add to add it.

**Comment by libardo** [comment]
Example with new version:
[EditableNumber(DefaultValue = null)]
public virtual int? MyNumber {get;set;}
