### ISSUE TITLE
Adding parts within another part's zone no longer works

### ISSUE THREAD

**Issue by laurachan** [n2cms/n2cms#677]
Since upgrading to N2CMS/Dinamico 2.8, I've found that I can no longer add parts to another part's zones via Organize Parts. I tested doing this in the latest version, 2.8.3, and it was also affected. I think this was working in version 2.7.x. 

Steps to reproduce:
1. Go to Organize Parts, add a new 2 Columns part to the page and save the part.
2. Drag another part, such as an image, into the Left zone of the 2 Columns part.
3. After editing and saving the image part, it is nowhere to be seen. There don't appear to be any parts inside the 2 Columns part. (To compare, adding an image part to the page's Below Content Area zone works fine).

**Comment by DejanMilicic** [comment]
@laurachan Should be fixed by this commit https://github.com/n2cms/n2cms/commit/91ff24360f8e43e2dc7de2845191feb66602e97b

**Comment by laurachan** [comment]
Thanks, it is indeed working again after upgrading to 2.8.4. Thank you @libardo for fixing the 2 Columns part's Bootstrap styles too.
