### ISSUE TITLE
Custom NavigationLinkPlugin doesn't generate correct Url query string of selected node

### ISSUE THREAD

**Issue by steeintw** [n2cms/n2cms#690]
I just upgraded from v2.3 and I have a custom NavigationLinkPlugin.
When I right click on a node, built-in context menu item such as "Add", "Edit".. will bring correct Url query string (?selected=/path/of/the/node/I-right-click-on/&n2item={id}). But my plugin does not. I have to left click on the node first (let the node "really" selected) so the "selected" parameter will generate correctly. But the "n2item" parameter will not generated anyway.

Below is my plugin definition, I use MVC controller, I wonder if this is the cause, but it worked before.
```
[NavigationLinkPlugin("Dispatch","dispatch", "/RegionDispatcher/?{Selection.SelectedQueryKey}={selected}", Targets.Preview, "{ManagementUrl}/Resources/icons/arrow_out.png", 70,
        GlobalResourceClassName = "Navigation",
        RequiredPermission = Permission.Write)]
    [Authorize(Roles = "Administrators")]    
    public class RegionDispatcherController : Controller
    {
       \\..........
    }
```

**Comment by libardo** [comment]
Did it ad n2item previously?

You can try this instead:
`
[N2.Edit.NavigationLinkPlugin("Dispatch", "dispatch", "{{appendSelection('/RegionDispatcher/')}}"
`

**Comment by steeintw** [comment]
Hi libardo,
    No, it didn't add n2item before.
    I tried your solution, the n2item is added to query string now, but the result is not correct. Please take a look at the following pictures. The "Support" page is selected, then I right click on "White Papers", the link of "Edit" is correct(Pic1), but the link of "Dispatch" is not correct(Pic2), it links to the "Support" page.

![pic1](https://cloud.githubusercontent.com/assets/1256295/11433849/43688a5e-94fe-11e5-8df7-73f03f4f6d71.png)
![pic2](https://cloud.githubusercontent.com/assets/1256295/11433848/43688450-94fe-11e5-932c-217a4961a28a.png)
