### ISSUE TITLE
Unable to load on or more of the requested types. Retrieve the LoaderExceptions property for more information

### ISSUE THREAD

**Issue by jv9** [n2cms/n2cms#691]
I got the following error since upgraded to v2.9. There is no this issue in the previous version. To resolve it, I have to remove all assemblies manually in BIN folder and rebuild the project. Any idea about this issue? 

![image](https://cloud.githubusercontent.com/assets/1653553/11263388/7e5517b2-8e47-11e5-94a2-12eed52b48dd.png)

**Comment by libardo** [comment]
Looks like AutoMapper.Net4 has some breaking changes (removed ConcurentDictionaryImpl<,>.Clear) which is referenced by some assembly in the bin folder. N2 doesn't depend on this but scans assemblies for content items and stuff. You can configure N2 to ignore these assemblies or upgrade this assembly which depends on Automapper.

**Comment by jv9** [comment]
Thanks for your answer. How can I configure N2 to ignore these assemblies? Can you show me an example for this? Thanks.

**Comment by libardo** [comment]
Try something like this
`
	<n2>
		<engine>
			<assemblies skipLoadingPattern="AutoMapper"></assemblies>
`
