### ISSUE TITLE
Parts added by [WithEditableChild] sometimes show up in the content tree in the management interface

### ISSUE THREAD

**Issue by laurachan** [n2cms/n2cms#693]
When we're in the N2 management interface and we either add a new page or edit details for an existing one, the content tree will add nameless entries for any parts that were included on the page through [WithEditableChild] attributes. Refreshing makes these entries disappear until the next time you add or edit a page.

![image](https://cloud.githubusercontent.com/assets/3029296/11347583/008c25f8-91d7-11e5-99d8-60548adf2784.png)

**Comment by bherila** [comment]
@laurachan this is caused by the "Show parts" option in the context menu
