### ISSUE TITLE
Feature req: SecurityManager

### ISSUE THREAD

**Issue by jsassner** [n2cms/n2cms#698]
I would like if you could make (in N2.Security.SecurityManager):

* public Permission GetPermissions(IPrincipal user, ContentItem item) - make it **virtual**
* private Permission GetPermiossions(IPrincipal user, ContentItem item, PermissionMap map) - make it **protected** instead

i.e:
public **virtual** Permission GetPermissions(IPrincipal user, ContentItem item)
**protected** Permission GetPermiossions(IPrincipal user, ContentItem item, PermissionMap map)

So i can override and access those two methods in my class inherited from the default SecurityManager.

**Comment by libardo** [comment]
Can you make a pull request?
