### ISSUE TITLE
FreeText.Required() causes StopExecutionException, which creates duplicate page

### ISSUE THREAD

**Issue by ahmadh21** [n2cms/n2cms#701]
```
Exception of type 'N2.Edit.Workflow.StopExecutionException' was thrown.
   at N2.Edit.Workflow.Commands.ValidateCommand.Process(CommandContext state) in c:\GitHub\n2cms\src\Framework\N2\Edit\Workflow\Commands\ValidateCommand.cs:line 10
```
We have a reproducible duplicate page scenario. Thankfully not very difficult to reproduce:

```asp.net
@model Dinamico.Models.ContentPage
@{
    Content.Define(re =>
    {
        re.Definition.Title = "Test page";
        re.FreeText("CustomText").Required();
        re.Text("Code").Required();
    });
}
@Html.Partial("LayoutPartials/Content")
```
1. Create a simple page template (like the one above)
2. Add that page, but when filling out the content keep CustomText blank and try to save
3. An internal *StopExecutionException* is thrown and caught, but now the user is brought back to the edit page to fill out CustomText (because it is required).
4. Fill out CustomText and save. Two pages will appear in the N2 list.

Text validation happens before submission, but the FreeText validation happens after submission. It looks like some version of the page is created before the FreeText validation, but the user isn't taken to the new saved version of the page. 

Maybe the solution is to redirect users to the edit page of the saved version on any internal exception while saving?

Thank you

**Comment by libardo** [comment]
Fixed by https://github.com/n2cms/n2cms/commit/200ffea002057fbd10c302da4c2bd6cd4c60551e
