### ISSUE TITLE
Organize parts generates invalid markup

### ISSUE THREAD

**Issue by DejanMilicic** [n2cms/n2cms#702]
version 2.9.6

In this version, as well for quite some time now, there is a problem with "organize parts" mode. Before, when entering that mode, each part on a page would be wrapped in a div tag that would provide wrapper with a small menu for editing each part.
However, what I am getting is following - wrapper divs are created, but not around parts. Instead they are all grouped at the bottom of the page, after last part. All of them are empty and hence they do not produce any visual appearance, making editing of parts impossible.

**Comment by libardo** [comment]
Sounds weird. How are you rendering the zone? Do you see the new control panel at the bottom of the page? 

If you need to you can configure the legacy control panel

` <n2>
    <edit>
	<organize useLegacyControlPanel="true"/>`

**Comment by DejanMilicic** [comment]
Yes, new control panel is rendering at top left corner and is completely operational. This was happening with old control panel and now with this new one.

Zone is rendered this way

`@Html.DroppableZone("ZoneName")`
