### ISSUE TITLE
New control panel and organize parts mode don't work when running N2CMS in an IIS application

### ISSUE THREAD

**Issue by laurachan** [n2cms/n2cms#703]
I just upgraded to N2CMS 2.9.6.2, and when I run our N2CMS project as a Local IIS application, the new control panel is missing. Also, when I switch to organize parts mode, existing parts are outlined in blue but hovering over them does not show the blue bar for editing the part, so I can neither add nor edit parts unless I use the legacy control panel or switch to running the project in IIS Express. If I switch to IIS Express, the new control panel and organize parts mode both work properly.

It looks like the issue is caused by some HTTP 404s when the browser tries to load the following resources. The 404s don't happen when I run the project with IIS Express.
* http://localhost/N2/App/i18n/en.js.ashx
* http://localhost/N2/App/Js/Directives.js
* http://localhost/N2/App/Js/Services.js
* http://localhost/N2/App/Preview/Preview.js

**Comment by libardo** [comment]
Which versions of IIS and IIS express are involved here? IS the same N2.zip file in both cases? What is changed in web.config and /N2/web.config since the version where it worked?

**Comment by laurachan** [comment]
* IIS Version 8.5
* Visual Studio 2013 with IIS Express version 10.0.10117.0
* N2.zip is being used and should be the same in both cases. Basically I've been testing with the same project but switching its web settings between IIS Express and Local IIS during testing. I rebuilt the project after switching just to be sure.
* No changes to either of the Web.config files; our version control system isn't listing either as modified.

Thanks.

**Comment by libardo** [comment]
Is the management UI also broken? en.js.ashx, Directives.js and Services.js are used from both places.

**Comment by laurachan** [comment]
Both the N2 management UI and fullscreen mode are missing the control panel and having the HTTP 404s. Other functions of the management UI seem to be working normally so far (e.g.: adding pages, edit page details).

**Comment by libardo** [comment]
This might be related to running N2 in a virtual directory application. Is the site not running from /?

**Comment by laurachan** [comment]
Apologies for the late reply; I've been AFK for the holidays.

Anyhow, I believe you're right, I did forget to mention that I was running the project in a virtual directory again, sorry about that. Thanks so much for taking care of this.

**Comment by laurachan** [comment]
Hi again. These 404 errors no longer occur in N2CMS 2.9.6.3, but now I get a different one when I run my N2CMS project in a virtual directory. The result is the new control panel still doesn't appear. If I switch to IIS express the new control panel works. 

Here's the error: `angular.js:8495 GET http://localhost/N2/App/Preview/PreviewBar.html 404 (Not Found)`
