### ISSUE TITLE
When using the legacy control panel in N2CMS 2.9.6.2, zones aren't highlighted when organizing parts

### ISSUE THREAD

**Issue by laurachan** [n2cms/n2cms#704]
If I use the legacy control panel, the highlighting for zones in organize parts mode doesn't appear anymore. When I start to drag and drop a part, only the names for the zones appear. 

![image](https://cloud.githubusercontent.com/assets/3029296/11850611/48f0c844-a3e3-11e5-977d-4598c8c389d7.png)

**Comment by libardo** [comment]
Fixed by https://github.com/n2cms/n2cms/commit/221f92f86aa09ac646faf63f90c1381f32434b37
