### ISSUE TITLE
Addable parts : scroll to the bottom of the page after adding

### ISSUE THREAD

**Issue by DejanMilicic** [n2cms/n2cms#707]
On a pages where addable parts are implemented, after amount of parts grows substantially, it becomes very unfriendly for the user to add and edit new parts. Reason for this is postback that occurs after adding, so editor is forced to scroll down to the bottom of the page in order to populate content after adding part.
Can this behavior be changed, so that page scrolls/jumps to the bottom after addable part is added?

**Comment by bherila** [comment]
Is the bottom really the best place? Ideally it would save the scroll position I guess.

**Comment by DejanMilicic** [comment]
Well, new parts are added to the bottom of the page... so it is basically same as position before postback. However, key problem is that editor adds new part at the bottom, postback occurs and then you have to scroll all the way to the bottom of the page in order to populate content.
Idela solution would be to implement ajax-based adding of the part.

**Comment by bherila** [comment]
> Idela solution would be to implement ajax-based adding of the part.

Well yeah, but that’s a lot of work :(
