### ISSUE TITLE
Auto unpublish

### ISSUE THREAD

**Issue by legomyego** [n2cms/n2cms#714]
Created, published content page. ->
Clicking unpublish on top menu (arrow at right side of Trash icon->unpublish) ->
Clicking edit on this page (right click->Edit) ->
Clicking save and publish (bottom menu) ->
Page is published, but after some time (1minute) it will be unpublished.
P.S. If in last step change action to: Clicking save and publish on top menu (arrow at right side of Trash icon->unpublish) - then page will be published normally and without auto unpublishing

**Comment by bherila** [comment]
Is this a feature request or an undesired, observed behavior? Which version?

**Comment by samfromlv** [comment]
I think this is issue. After you "Save and publish" page should stay published but flips back to unpublished. We observer same behavior with 2.6.3.8.

**Comment by bherila** [comment]
This is working for me properly now. If the Expiration date of the page passes, however, it might become unpublished again.
