### ISSUE TITLE
Minus symbol in URL maker title cause errors

### ISSUE THREAD

**Issue by legomyego** [n2cms/n2cms#724]
![image](https://cloud.githubusercontent.com/assets/5999603/14380143/b12ca372-fd86-11e5-8950-1e2c23e13038.png)

If I will try to create Url maker with such title , i will get error:

![image](https://cloud.githubusercontent.com/assets/5999603/14380161/c4bd87da-fd86-11e5-8b53-d750b57ebd6e.png)

N2 version - 2.6.3.8

**Comment by bherila** [comment]
@legomyego can you check if this is solved in the latest released nuget packages?

**Comment by bherila** [comment]
Closing due to no response from the OP
