### ISSUE TITLE
Brute force login protection

### ISSUE THREAD

**Issue by laurachan** [n2cms/n2cms#725]
It would be nice if the login page for the N2 management interface had some form of protection against brute-force login attempts (e.g.: to stop/hinder someone intent on defacing the site). Locking out accounts might not be necessary, but some form of throttling or gradual slowdown on successive failed login attempts would slow down someone making rapid-fire login attempts.

**Comment by bherila** [comment]
This would be a nice feature to have, and I can support anyone who wants to send a PR that will add it.

**Comment by bherila** [comment]
Closing the request for now. Feel free to reopen with a pull request. As a workaround, put cloudflare in front of your N2 instance, or restrict the /N2 folder in IIS with IP filtering or something.
