### ISSUE TITLE
Problem loging in if upload folder containes lots of files and selected folder is /upload/

### ISSUE THREAD

**Issue by ja1984** [n2cms/n2cms#732]
Hi!

We have a site that have ALOT of files and folders in the upload folder, ~35k files.

Whenever we sign in to N2 and the last folder we had open was /upload/ the Context.ashx/full requests takes "forever" and eventually times out.

I don't really know how to handle this, maybe there is a work around of some sort, except for manually changing the selected value in the database?

**Comment by bherila** [comment]
Hi @ja1984 , sorry for the delay.

You can increase the general request timeout in web.config, or you can move the files into subfolders. In general, performance characteristics of directories decline linearly with the size of the directory.
