### ISSUE TITLE
Where did commits for 2.9.6.8 go ?

### ISSUE THREAD

**Issue by Tazer** [n2cms/n2cms#733]
Hey,

What happend to the commits beyond 2.9.6.5 ? Cause 2.9.6.8 is on nuget and I know I have seen commits newer then the current ? 

Why was the master branch "force pushed" ? @libardo  @bherila

**Comment by Tazer** [comment]
Now it's seems back , maybe an github issue ?

**Comment by bherila** [comment]
I think it was a rebasing issue.
