### ISSUE TITLE
[critical] Parts will not save data

### ISSUE THREAD

**Issue by vialeda** [n2cms/n2cms#734]
Version: 2.9.6.8
Hello,  I made a simple Parts described below and when I want to publish the Part after I inserted it in a Zone I got an error

> String or binary data would be truncated.
> The statement has been terminated.

Here the code:

**The part controller**
```
/// <summary>
    /// This controller returns a view that displays the item created via the management interface
    /// </summary>
    [Controls(typeof(HeaderTopBarPart))]
    public class HeaderTopBarPartController : ContentController<HeaderTopBarPart>
    {
        public override ActionResult Index()
        {
            return PartialView("~/Dinamico/Themes/Pixma/Views/ContentParts/HeaderTopBarPart.cshtml", CurrentItem);
        }
    }
```

**The model class**
```
/// <summary>
    /// This class represents the data transfer object that encapsulates 
    /// the information used by the template.
    /// </summary>
    [PartDefinition("HeaderTopBarPart")]
    public class HeaderTopBarPart : PartModelBase, IPart
    {
        [EditableText("PhoneNumber", 100, SortOrder = 0)] // The label name in the admin panel
        public virtual string PhoneNumber
        {
            get { return (string)(GetDetail("PhoneNumber") ?? string.Empty); } // The prop name used for database.
            set { SetDetail("PhoneNumber", value, string.Empty); } // The prop name used for database.
        }
        [EditableText("Email", 100, SortOrder = 1)]
        public virtual string Email
        {
            get { return (string)(GetDetail("Email") ?? string.Empty); }
            set { SetDetail("Email", value, string.Empty); }
        }
        [EditableText("FacebookUrl", 100, SortOrder = 3)]
        public virtual string FacebookUrl
        {
            get { return (string)(GetDetail("FacebookUrl") ?? string.Empty); }
            set { SetDetail("FacebookUrl", value, string.Empty); }
        }
        [EditableText("TwitterUrl", 100, SortOrder = 4)]
        public virtual string TwitterUrl
        {
            get { return (string)(GetDetail("TwitterUrl") ?? string.Empty); }
            set { SetDetail("TwitterUrl", value, string.Empty); }
        }
        [EditableText("LinkedInUrl", 100, SortOrder = 5)]
        public virtual string LinkedInUrl
        {
            get { return (string)(GetDetail("LinkedInUrl") ?? string.Empty); }
            set { SetDetail("LinkedInUrl", value, string.Empty); }
        }
        [EditableText("DribbbleUrl", 100, SortOrder = 6)]
        public virtual string DribbbleUrl
        {
            get { return (string)(GetDetail("DribbbleUrl") ?? string.Empty); }
            set { SetDetail("DribbbleUrl", value, string.Empty); }
        }
    }
```

**The view file**
```
@model N2Website.Dinamico.Controllers.Models.Parts.HeaderTopBarPart
<div class="top-bar">
    <div class="slidedown collapse">
        <div class="container">
            <div class="phone-email pull-left">
                <a><i class="fa fa-phone"></i>&nbsp;@Model.PhoneNumber </a>
                <a href="support@fifothemes.com"><i class="fa fa-envelope"></i>&nbsp;@Model.Email</a>
            </div>
            <div class="pull-right">
                <ul class="social pull-left">
                    @if (!string.IsNullOrEmpty(Model.FacebookUrl))
                    {
                        <li class="facebook"><a href="@Model.FacebookUrl" target="_blank"><i class="fa fa-facebook"></i></a></li>
                    }
                    @if (!string.IsNullOrEmpty(Model.TwitterUrl))
                    {
                        <li class="twitter"><a href="@Model.TwitterUrl" target="_blank"><i class="fa fa-twitter"></i></a></li>
                    }
                    @if (!string.IsNullOrEmpty(Model.LinkedInUrl))
                    {
                        <li class="linkedin"><a href="@Model.LinkedInUrl" target="_blank"><i class="fa fa-linkedin"></i></a></li>
                    }
                    @if (!string.IsNullOrEmpty(Model.DribbbleUrl))
                    {
                        <li class="dribbble"><a href="@Model.DribbbleUrl" target="_blank"><i class="fa fa-dribbble"></i></a></li>
                    }
                </ul>
            </div>
        </div>
    </div>
</div>
```

**The stack trace**
Stack Trace: 

> [SqlException (0x80131904): String or binary data would be truncated.
> The statement has been terminated.]
>    System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) +2442030
>    System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) +5736648
>    System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) +628
>    System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) +3731
>    System.Data.SqlClient.SqlDataReader.TryConsumeMetaData() +58
>    System.Data.SqlClient.SqlDataReader.get_MetaData() +89
>    System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString) +379
>    System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest) +2026
>    System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite) +375
>    System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method) +53
>    System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method) +240
>    System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior) +41
>    System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader() +14
>    NHibernate.AdoNet.AbstractBatcher.ExecuteReader(IDbCommand cmd) +279
>    NHibernate.Id.InsertSelectDelegate.ExecuteAndExtract(IDbCommand insert, ISessionImplementor session) +46
>    NHibernate.Id.Insert.AbstractReturningDelegate.PerformInsert(SqlCommandInfo insertSQL, ISessionImplementor session, IBinder binder) +77
> 
> [GenericADOException: could not insert: [N2Website.Dinamico.Controllers.Models.Parts.HeaderTopBarPart][SQL: INSERT INTO n2Item (ParentID, Title, Name, ZoneName, TemplateKey, TranslationKey, Created, Updated, Published, Expires, SortOrder, Visible, VersionOfID, SavedBy, AncestralTrail, VersionIndex, State, ChildState, AlteredPermissions, Type) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'HeaderTopBarPart'); select SCOPE_IDENTITY()]]
>    NHibernate.Id.Insert.AbstractReturningDelegate.PerformInsert(SqlCommandInfo insertSQL, ISessionImplementor session, IBinder binder) +210
>    NHibernate.Persister.Entity.AbstractEntityPersister.Insert(Object[] fields, Boolean[] notNull, SqlCommandInfo sql, Object obj, ISessionImplementor session) +205
>    NHibernate.Persister.Entity.AbstractEntityPersister.Insert(Object[] fields, Object obj, ISessionImplementor session) +184
>    NHibernate.Action.EntityIdentityInsertAction.Execute() +150
>    NHibernate.Engine.ActionQueue.Execute(IExecutable executable) +25
>    NHibernate.Event.Default.AbstractSaveEventListener.PerformSaveOrReplicate(Object entity, EntityKey key, IEntityPersister persister, Boolean useIdentityColumn, Object anything, IEventSource source, Boolean requiresImmediateIdAccess) +498
>    NHibernate.Event.Default.AbstractSaveEventListener.PerformSave(Object entity, Object id, IEntityPersister persister, Boolean useIdentityColumn, Object anything, IEventSource source, Boolean requiresImmediateIdAccess) +298
>    NHibernate.Event.Default.AbstractSaveEventListener.SaveWithGeneratedId(Object entity, String entityName, Object anything, IEventSource source, Boolean requiresImmediateIdAccess) +124
>    NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.SaveWithGeneratedOrRequestedId(SaveOrUpdateEvent event) +35
>    NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.EntityIsTransient(SaveOrUpdateEvent event) +78
>    NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.PerformSaveOrUpdate(SaveOrUpdateEvent event) +89
>    NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.OnSaveOrUpdate(SaveOrUpdateEvent event) +203
>    NHibernate.Impl.SessionImpl.FireSaveOrUpdate(SaveOrUpdateEvent event) +316
>    NHibernate.Impl.SessionImpl.SaveOrUpdate(Object obj) +305
>    N2.Persistence.NH.NHRepository`1.SaveOrUpdate(TEntity entity) in c:\GitHub\n2cms\src\Framework\N2\Persistence\NH\NHRepository.cs:182
>    N2.Edit.Versioning.VersionManager.Replace(ContentItem currentItem, ContentItem replacementItem) in c:\GitHub\n2cms\src\Framework\N2\Edit\Versioning\VersionManager.cs:182
>    N2.Edit.Versioning.VersionManager.ReplaceVersion(ContentItem currentItem, ContentItem replacementItem, Boolean storeCurrentVersion) in c:\GitHub\n2cms\src\Framework\N2\Edit\Versioning\VersionManager.cs:131
>    N2.Edit.Versioning.VersioningExtensions.MakeMasterVersion(IVersionManager versionManager, ContentItem versionToPublish) in c:\GitHub\n2cms\src\Framework\N2\Edit\Versioning\VersioningExtensions.cs:142
>    N2.Edit.Versioning.VersioningExtensions.Publish(IVersionManager versionManager, IPersister persister, ContentItem previewedItem) in c:\GitHub\n2cms\src\Framework\N2\Edit\Versioning\VersioningExtensions.cs:171
>    N2.Edit.PublishPreview.OnInit(EventArgs e) in C:\GitHub\n2cms\src\Mvc\MvcTemplates\N2\Content\PublishPreview.aspx.cs:20
>    System.Web.UI.Control.InitRecursive(Control namingContainer) +139
>    System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +1580

Notice that I downloaded the Dinamico templates package and updated every packages to get to 2.9.6.8. Website was running successfully except about the Part save.

**Comment by ahmadh21** [comment]
Hi,

It looks like one of the table columns is too small. You might be able to fix this by increasing the length of the column in the database.

**Comment by bherila** [comment]
If you do this and find that one of our predefined lengths is too small, please open a new ticket or PR so that we can increase the length in the schema.
