### ISSUE TITLE
n2 control panel inserts slash after hash in url

### ISSUE THREAD

**Issue by kodeo** [n2cms/n2cms#736]
`http://mysite/mypage#mysection` 

becomes:

`http://mysite/mypage#/mysection `

when the control panel is showing, thereby breaking anchors.

**Comment by kodeo** [comment]
Hello. Is there anybody out there?

**Comment by kodeo** [comment]
Further to this, it seems the bug was introduced between versions 2.9.5.5 and 2.9.6, which coincides with the control panel being moved from the top left to the bottom left corner. I am at a loss to explain how or why the URL should be interfered with in this way.

Just to reiterate, this issue breaks all use of URL fragments, as used by surely almost all web sites. It is reproducible on a completely vanilla installation of n2.

**Comment by bherila** [comment]
Hi @kodeo where is the URL appearing like this? 

Even better, can you find the commit that has caused this behavior? Happy to fix it or take a PR but I'm not seeing the issue myself.

Thanks,
Ben

**Comment by kodeo** [comment]
Hi @bherila. Narrowing it down any further is beyond my abilities I fear but here's a demo of the issue in a minimal MVC app, which is just a default Visual Studio MVC project with N2CMS.Management -Version 2.9.6 and N2CMS.MVC -Version 2.9.6 added via nuget, with HomePage and RootNode models added, plus a HomePage controller and view. Run though the installation wizard then hit the home page with an anchor and you should see that /#foo will redirect you to /#/foo.

https://s3-eu-west-1.amazonaws.com/n2issuedemo/n2issue.7z

**Comment by bherila** [comment]
Okay, I’m going to try to reproduce the issue on my end. Thank you for the information!

**Comment by ja1984** [comment]
This behavior breaks websites using libraries such as Pager.js for singel page applications that rely on #! in the url.

**Comment by ja1984** [comment]
After hours of debugging I managed to find a solution

```
n2.preview.directive("n2PreviewParts", [function () {
    return {
        controller: function ($scope, Context, **$location,**  Content, ZoneOperator, Reveal) {, 
```

Removing $location here doesn't seem to affect anything, but it solved the problem with angular automatically replacing # with #/

**Comment by libardo** [comment]
Nicely done! I committed your proposed solution (no need to make a pull request). Please re-open if this didn't resolve the issue.
