### ISSUE TITLE
Dependency issue with N2CMS Nuget package

### ISSUE THREAD

**Issue by laurachan** [n2cms/n2cms#738]
Hi there,

I noticed that the N2CMS Nuget package lists N2CMS.Search.Lucene 2.9.6.11+ as a dependency. However, the highest version of the N2CMS.Search.Lucene package is 2.9.6.8. This makes installing or upgrading the N2CMS package error out. 

Thanks.

**Comment by bherila** [comment]
I need access to the package. I was not able to deploy all the packages because I don't have access on nuget.org @libardo

**Comment by DejanMilicic** [comment]
@bherila Can you please tell me exact name of the package you need an access to? I checked "N2CMS" and you are listed as an owner there.

**Comment by bherila** [comment]
Hi @laurachan  and @DejanMilicic  I think the dependency resolution has been resolved. 

@libardo I still need access to these packages:

* N2CMS.Management.Statistics
* N2CMS.Management.Targeting

@laurachan you can use the MyGet feed to update in the meantime:

> **For development ("bleeding edge") packages**, you can add our MyGet feed to your NuGet package manager. Please follow the instructions in NuGet documentation for doing this. Here are the feed URLs:
> 
> * NuGet V3 feed URL (Visual Studio 2015+): https://www.myget.org/F/n2cms/api/v3/index.json
> * NuGet V2 feed URL (Visual Studio 2012+): https://www.myget.org/F/n2cms/api/v2
>

**Comment by DejanMilicic** [comment]
@laurachan I just installed N2CMS package from nuget (version 2.9.6.11 and everything went well. Can you please try now and confirm it works for you too?

**Comment by laurachan** [comment]
@DejanMilicic I just tried installing the N2CMS package on a new project and it worked. Thanks for fixing this @bherila!
