### ISSUE TITLE
Performance of upload folder

### ISSUE THREAD

**Issue by Tazer** [n2cms/n2cms#741]
Hello,

We are having issues with the upload folder, we have around 30k files within sub-folders.
But when N2 admin is loading it seems it tries to access all the files to be able  to build the menu.

Would be nice to get some optimizations here, or atleast so it's async. Cause now n2 admin will just load for an infinity , if the upload folder was selected "last time". 

Our data is 30k files and around 8gb of data.

**Comment by bherila** [comment]
I think a suitable workaround might be to build an in-memory cache of the upload folder. Is this still an issue for you @Tazer ?

**Comment by bherila** [comment]
Closing due to no response from @Tazer , please feel free to reopen if needed.
