### ISSUE TITLE
Many website links broken

### ISSUE THREAD

**Issue by naasking** [n2cms/n2cms#745]
Many of the links on your website, n2cms.com, are are app-relative, but not resolving. For instance, your link for view templates is http://n2cms.com/~/Documentation/Templates.aspx, which obviously won't resolve.

Ditto for screenshots, features, etc.

**Comment by bherila** [comment]
The website needs a revamp which was started but never completed. 

Moving to https://github.com/n2cms/n2cms_com/issues/8
