### ISSUE TITLE
EditableChildren reordering not being published

### ISSUE THREAD

**Issue by kodeo** [n2cms/n2cms#757]
When changing the order of EditableChildren content using the white-on-blue up and down arrows, the new order though reflected at the time in the preview is lost on publishing.

**Comment by bherila** [comment]
Not sure why this would be happening... which storage engine are you using?

**Comment by SntsDev** [comment]
Hi there, I have the same problem. After re-ordering, a message saying "This is a version of another item" appears. Even if you go to drafts and publish it, the re-ordering doesn't work. So we have to use the right sidebar to do the re-ordering which usually works (not always though). We're using SQL Server 2008 R2 (10.50).

**Comment by kodeo** [comment]
Further to this, I've just upgraded N2CMS.Management from version 2.9.6.8 to 2.9.6.14 and it's working properly now, so it would appear the issue has been fixed somewhere in between.
