### ISSUE TITLE
N2CMS.ReusableParts.2.9.6.14 does not create a lib folder with dlls

### ISSUE THREAD

**Issue by Hypnobrew** [n2cms/n2cms#759]
Hi

N2CMS.ReusableParts.2.9.6.14 does not create the correct lib folder with dlls in the /packages folder, when installed via Nuget.

N2CMS.ReusableParts.2.9.6.13 seem to work just fine!

![n2cms reusableparts](https://cloud.githubusercontent.com/assets/746489/19676428/9f890fc4-9a94-11e6-8fce-8ed33ca60454.PNG)

**Comment by bherila** [comment]
Hi @Hypnobrew , this should be working now. I just spun up a project and it worked fine. Let me know if you are still having an issue with it. Sorry for the extremely delayed response.

Thanks,
Ben
