### ISSUE TITLE
Problem with resources config

### ISSUE THREAD

**Issue by DKotoski** [n2cms/n2cms#761]
Hello,
I needed to put a local ckeditor in the n2cms site so i can customize the functions of the editor.
I have tried putting <resources ckEditorPath = "/Scripts/ckeditor/ckeditor"/> in the config it didnt work.
Noticed that I have to define it in config sections and found an answer about that.
But  after that not working went to look in the dll to see that N2.Configuration.ResourcesSection doesn't exist. 
With that problem I am not able to take any resources locally.
The current version of N2.dll is 2.9.6.8

**Comment by bherila** [comment]
Hi @DKotoski is this still a problem? I believe the resources section is working properly at this time.
