### ISSUE TITLE
404  /N2/Api/Context.ashx

### ISSUE THREAD

**Issue by LobalOrning** [n2cms/n2cms#764]
Fresh Install using NuGet Package N2CMS ( have tried 2.9.6.8 and 2.9.6.14 & .16)

After DB setup and setting Root/StartPage, try to access /N2, and get
<img width="856" alt="screen shot 2016-11-22 at 1 37 55 pm" src="https://cloud.githubusercontent.com/assets/638240/20537029/824528ae-b0b9-11e6-947e-838c8e6767aa.png">

**Comment by bherila** [comment]
Can you please upload the web.config in the N2 folder to a gist.github.com 

I have seen this before...

Thanks,
Ben

**Comment by LobalOrning** [comment]
https://gist.github.com/LobalOrning/35508c2139e46350744fe59501f85164

**Comment by LobalOrning** [comment]
What's interesting, is that all the 'locations' specified in the web.config exist as directories, except API.

eg: <location path="Files/FileSystem/UploadFile.ashx">
Using the No-Zip package (or UnZipping the Zip package), I can see the directory Files/FileSytem ...

But Api doesn't exist; hope this helps ?

**Comment by bherila** [comment]
Hmm for me the problem was a mangled web.config - but yours looks right. 

Here is my known good web.config: https://gist.github.com/bherila/c190ffaba1df0a5b897310f6a6e5d687

it it identical to yours! 

Here is another question... look at the web.config in the root. Do you have this node?

```
	<modules runAllManagedModulesForAllRequests="true">
			<add name="n2.initializer" type="N2.Web.InitializerModule, N2" />
		</modules>
```

**Comment by LobalOrning** [comment]
I have that as well. Below I have listed the steps I'm using to create a new site, can you tell me if I'm doing something wrong, or where you are doing something different.

1. In Sql Express create new Database 'test_cms'

2. Using Visual Studio, File > New Project 
  - .NET Framework 4.6.1 ( have used 4.5 as well, with no difference )
  - ASP.Net Web Application
  - MVC Template for 4.6.1 with No Authentication
  
3. Manage NuGet Packages for the web project
  - Browse: n2cms
  - Install N2CMS : latest stable version 2.9.6.16

4. In the Models folder add new Class RootPage
   - https://gist.github.com/LobalOrning/fac3bc07c407ac479a6f811cf72516b0

5. In the Models folder add a new Class StartPage
   - https://gist.github.com/LobalOrning/d57b15670aaeb3e74b33bdb71a22174f

6. Add N2CMS connection string to ConnectionStrings section of web project web.config
  - ConnectionString: '< add name="N2CMS" connectionString="Server=.\SQLExpress;Initial Catalog=test_cms;Integrated Security=True;" / >'

7. Run the web project using IIS Express

8. Site automatically navigates to http://localhost:61793/N2/Installation/Begin/Default.aspx?action=install
<img width="840" alt="screen shot 2016-12-01 at 10 01 13 am" src="https://cloud.githubusercontent.com/assets/638240/20799005/d7e6ca1e-b7ae-11e6-84cb-b53f3135a2ad.png">

  - Change password
  - Click OK

9. Site navigates to http://localhost:61793/N2/Installation/Default.aspx
<img width="833" alt="screen shot 2016-12-01 at 10 02 45 am" src="https://cloud.githubusercontent.com/assets/638240/20799049/0235f38a-b7af-11e6-8963-6af1293b8f4f.png">

  - Click Create Tables
  - Click OK on dialog box to confirm table creation

10. Site navigates to http://localhost:61793/N2/Installation/Default.aspx#Database
<img width="827" alt="screen shot 2016-12-01 at 10 04 06 am" src="https://cloud.githubusercontent.com/assets/638240/20799068/11738f2e-b7af-11e6-8c68-d736bcb78244.png">

  - Click on Step2 inside green Alert section

11. Site navigates to http://localhost:61793/N2/Installation/Default.aspx#Content
<img width="815" alt="screen shot 2016-12-01 at 10 05 09 am" src="https://cloud.githubusercontent.com/assets/638240/20799081/1d76f342-b7af-11e6-8cd0-07be5ebed8be.png">

  - In the Manually insert nodes section: select RootPage in the [root node] drop down, and selection Home Page in the [start node] drop down
  - Click Add two separate nodes button

12. Site navigates to http://localhost:61793/N2/Installation/Default.aspx#Content
<img width="839" alt="screen shot 2016-12-01 at 10 07 19 am" src="https://cloud.githubusercontent.com/assets/638240/20799096/28278f4a-b7af-11e6-9501-5459cfd93590.png">

  - Click Step3 in green Alert section

13. Site navigates to http://localhost:61793/N2/Installation/Default.aspx#Finish
<img width="821" alt="screen shot 2016-12-01 at 10 08 17 am" src="https://cloud.githubusercontent.com/assets/638240/20799109/31567144-b7af-11e6-8f31-c5c5f3ac818e.png">

  - Click Disable installation in config button

14. Site navigates to http://localhost:61793/N2/#Finish
<img width="619" alt="screen shot 2016-12-01 at 10 10 06 am" src="https://cloud.githubusercontent.com/assets/638240/20799113/3589ee62-b7af-11e6-8c06-a7e23163f812.png">

  - Error is thrown

**Comment by bherila** [comment]
Did you install a management package as well? 

 

Normally I DO NOT install the N2CMS package. Instead I install the following packages: 

 

1.       N2cms.Management.Nozip

2.       N2cms.Dinamico

 

Then I run the project and configure the database as you specified. I do not need to manually create new class for RootPage or StartPage. 

 

Personally I have never used the N2CMS MVC Template, I always use Dinamico as I prefer the Razor templates

 

Give that a try and let me know if you are still having issues. What I will offer to do is create a new solution and upload it here on Github as a release of the latest tag, then people can download and use that as a starting point. 

 

Hopefully this will help! I feel badly about how hard this has been to pin down :(

 

Thanks,

Ben

**Comment by LobalOrning** [comment]
Ben,

Thank you very much for the time you have taken to review my issue. I was able to get a new project started using the N2CMS.NoZip and N2CMS.MVC package.

After doing this, I wondered what the difference was between the working project and the non-working project.

From what I can tell, the missing item from the N2CMS standalone package, is a file called CmsConfig.cs. Without this file any project created always throws the same 404 error. 

Maybe you could remove old documentation and web sites that have obsolete information, they create a rabbit hole of misinformation. You can use your GitHub documentation to state that if you use the N2CMS standalone NuGet, you still need either N2CMS.Dinamico or N2CMS.MVC NuGet for it to work properly. 

As well, it was really hard for me to find the Attributes needed to create the RootPage and StartPage. I couldn't actually find it in the documentation anywhere. As, I understand it, the Dinamico package makes that unnecessary; however, the MVC and standalone N2CMS package still need those to move beyond Step 2. If you don't create and decorate those classes, the [root node] and [start node] drop-down menus don't contain anything to select.

Again, thanks for all your help.

Josh

**Comment by bherila** [comment]
Thank you @LobalOrning /Josh for sticking with us through this.  I'm not an expert in everything N2 so I appreciate the feedback and I've also updated the README file according to your suggestions (I agree wholeheartedly!)

I would LOVE it if someone had the time to add some checks to the N2 Admin code that will throw meaningful exceptions if files and/or classes are missing. It would make troubleshooting these kind of problems a LOT easier and probably support additional community enhancements.

Regards,
Ben
