### ISSUE TITLE
Security and roles when using GetChildren and AccessFilter

### ISSUE THREAD

**Issue by freke1981SWE** [n2cms/n2cms#770]
Hello! We want to change how the role and permissions is handled. Now it seems that Everyone is overrrides the other roles that are set. 

For example if we have a page with permission Everyone we want to use that for non logged in users. But if the user logins we only want to take the current user role in account when getting the menu items etc. Today we use this code the get menu items:

```
 return item.GetChildren(
                new AllFilter(
                    new AccessFilter(),
                    new PageFilter()
                )
            );
```

But it seems that the AccessFilter need to be customized...any idéas?

**Comment by bherila** [comment]
By definition, shouldn't "Everyone" include signed-in users? I am confused what you are trying to do.

**Comment by DejanMilicic** [comment]
@freke1981SWE Does this mean you want to use one set of rules for unauthenticated users and another set of access rules for authenticated users? Can you please give an example of what does not work for you with current implementation?
