### ISSUE TITLE
Part shows in "Add-part" list even if "AuthorizedRoles" is set

### ISSUE THREAD

**Issue by empaortberg** [n2cms/n2cms#774]
I can still see the option in the list, but when i try to add it i cant select a zone, which is good. But why can i see the part in the "add-part" list if the AuthorizedRoles is meant to hide it?

**Comment by bherila** [comment]
I guess the Add Part list is not checking the AuthorizedRoles. I am not sure how this code works, perhaps @libardo can advise when he has a moment.

**Comment by empaortberg** [comment]
I have done a pull-request with a solution on my problem.

**Comment by bherila** [comment]
Thanks @empaortberg I am merging this into the latest package. 

https://github.com/n2cms/n2cms/pull/775
