### ISSUE TITLE
Confirm dialog when deleting users

### ISSUE THREAD

**Issue by rewdboy** [n2cms/n2cms#782]
It would be really really good with a confirm dialog box when clicking delete on a user. I have manually fixed this in my own site by adding visible="false" to the existing button and then adding a <TemplateField> with a button with a confirm.
Like so

```

<asp:ButtonField Text="delete" CommandName="Delete" visible="false" meta:resourcekey="ButtonColumnResource1" runat="server" />


<asp:TemplateField>
            <ItemTemplate>
                <asp:Button ID="Button1" runat="server" CommandName="Delete" OnClientClick="return confirmDelete()" Text="Delete" />
            </ItemTemplate>
 </asp:TemplateField>
```

N2 version 2.9.6.2

**Comment by DejanMilicic** [comment]
@rewdboy Thanx for nice UX tip!
