### ISSUE TITLE
Slow startup when debugging...

### ISSUE THREAD

**Issue by freke1981SWE** [n2cms/n2cms#784]
Each time I debug my project it takes several minutes for everything to load up. I can see in the Diagnostic tools that there are lots of database calls like (select contentite...). Our test database has several hundreds of N2 pages. Is it the route setup that causes all these calls and long boot time? Any idéas how to speed this up?

**Comment by bherila** [comment]
Hmm @freke1981SWE can you install DotTrace and profile the app to see what is taking so long? As a N2 contributor (thanks again for your past contributions) you are eligible for a free license, so you can install the trial for now and we can help you out with the license 😄 

(send me an email ben -at herila dot net and I will get you added to our Jetbrains account)

**Comment by bherila** [comment]
Closing due to no response from the OP
