### ISSUE TITLE
Roles list page redirection url issue

### ISSUE THREAD

**Issue by govindajindal** [n2cms/n2cms#790]
Hi Team,

I have found one bug into n2cms code i.e. when n2cms admin user will click on Roles button (left top side) then he will get 404 error message because of wrong redirection into code for Roles.aspx page

I have added screenshot below for reference. currently "~/N2Extensions/Roles/Roles.aspx" is given for redirect which is wrong it should be "{ManagementUrl}/Roles/Roles.aspx".

![image](https://cloud.githubusercontent.com/assets/17876201/26518320/ffcff9da-42cb-11e7-88fa-c6a1daa4de79.png)

**Comment by bherila** [comment]
Closing thanks to your PR #791 

Thanks and sorry for the slowness on my end!

**Comment by govindajindal** [comment]
Please let me know, when the code updates will be available in .Net nuget package update and what will be the version number??
