### ISSUE TITLE
Setup and use N2CMS on the latest mono v5 under Debian Jessie

### ISSUE THREAD

**Issue by sanyo-ok** [n2cms/n2cms#796]
Hello,

1) Can you please create a manual on installing your CMS on Mono v5
http://www.mono-project.com/download/#download-lin-debian

Taking into account resolved issue:
https://github.com/n2cms/n2cms/issues/769

It seems you already tried to run the N2CMS under Linux.
Does it succeed? Are there any more issues related to using it under Linux?

Btw, may be you know, do popular WebForms  components like DevExpress or Syncfusion Grid work on Linux Mono v5 ?

2) It seems your site http://n2cms.com/ in offline

> Cannot find start page
>Here are a few known causes.
>Site Not Installed

**Comment by bherila** [comment]
As far as I know, n2cms cannot be run under mono at this time.

**Comment by sanyo-ok** [comment]
Will it ever happen N2CMS to run under Mono?

Does N2CMS run on MS DotNet v4.0 ?

When do you plan to restore N2CMS.com website?

**Comment by bherila** [comment]
n2cms is tested and works on .net 4.5 with asp.net mvc on Windows

**Comment by DejanMilicic** [comment]
I do not think N2CMS will ever run under Mono - of course, unless some individual decides to devote a substantial amount of time to this task. In great scheme of things, Mono is basically dead - .Net Core is way to go.

**Comment by sanyo-ok** [comment]
According to
http://www.mono-project.com/docs/about-mono/releases/5.0.0/

> Reference assemblies

>The reference assemblies were updated to fully match the .NET 4.6.2 API set. This means that you no longer get compilation errors about missing classes/methods when building against one of the .NET profiles via msbuild/xbuild.

>Note that at runtime certain APIs that Mono doesn’t (yet) implement will still throw an exception.

**Comment by sanyo-ok** [comment]
.NET Core does not support WebForms which is used in your project.

Do you plan to support .Net Core any soon?

According to https://github.com/n2cms/n2cms/issues/624

>Any more news on Asp.net Core / Mvc 6?

>@bherila
Contributor
bherila commented on May 12, 2016

>I don't know of a particular reason why we need that... but we'd definitely work with anyone who wanted to build that out and submit a PR. There are still some dependencies on web forms, so this is likely a larger undertaking.

**Comment by sanyo-ok** [comment]
Does not it look like Mono is not dead and support of Mono is more feasible than .Net Core?

**Comment by bherila** [comment]
That's from over a year ago. 

If you can get N2 working on Mono, we'd take a pull request and make it official. But I don't have plans to add Mono support at this time.

**Comment by sanyo-ok** [comment]
> I do not think N2CMS will ever run under Mono - of course, unless some individual decides to devote a substantial amount of time to this task. In great scheme of things, Mono is basically dead - .Net Core is way to go.

Do you and bherila plan to support DotNet Core sometimes in the future?
May be in 1-2 years later when hHibernate v5 and other libraries you are using support DotNet Core too?

Right now is there a docker image with N2CMS for Windows?

**Comment by bherila** [comment]
There is not a docker image. N2CMS installs as a series of Nuget packages into a VS Web Application project.

**Comment by sanyo-ok** [comment]
What about future support of DotNet Core?

**Comment by bherila** [comment]
We do not have plans to remove the dependency on Web Forms at this time.
