### ISSUE TITLE
EditableTags auto-complete issue, not working

### ISSUE THREAD

**Issue by SntsDev** [n2cms/n2cms#798]
**_EditableTags_** control.

Apart from the fact that the jQuery plug-in is out-dated and un-maintained (2015) everything works fine, **except the auto-complete part**.

It calls the Ajax handler and it responds, however, it seems that another handler is responding instead of `src/Mvc/MvcTemplates/N2/Content/Tags/TagsAjaxService.cs`

For instance, this is the call:
```
../N2/tags.n2.ashx?tagName=TagsCollection&action=tags&selected=%2foverview%2f&term=b
```
And the answer is always:
```json
{
    "Current": null
}
```
...no matter what page or term it is written. I'm being unable to build right now, the csproj is not working well in VS2015. How can we trace which service is handling this request?

Thanks!

**Comment by bherila** [comment]
I am not able to build until we upgrade the projects to VS2017. Unfortunately, I don't have sufficient time or experience with MSBUILD to help with this. See also: https://github.com/n2cms/n2cms/issues/787

**Comment by DejanMilicic** [comment]
@SntsDev this is service handling request
https://github.com/n2cms/n2cms/blob/c4fa5f8ed440ed0c172166534808ad209bd0489b/src/Mvc/MvcTemplates/N2/Content/Tags/TagsAjaxService.cs

**Comment by SntsDev** [comment]
Thanks @DejanMilicic. Yes, it is expected that **TagsAjaxService.cs** handles those requests. However, as you can see from my answer, the response doesn't correspond to that service.

**Comment by DejanMilicic** [comment]
@SntsDev Can you please give me brief instructions how to reproduce this (how to create new tags, etc) and I will take care of this?
