### ISSUE TITLE
Email Form and TLS 1.2

### ISSUE THREAD

**Issue by ahmed205** [n2cms/n2cms#811]
Hi 

My Server is enabled only TLS 1.2 and the TLS 1.0 and TLS 1.1 is disabled, its show error 

The client and server cannot communicate, because they do not possess a common algorithm

how can i fix it?

**Comment by DrArtz** [comment]
From an outside view, you need to enable a lower security standard on that box until N2CMS gets up to spec on security standards - if you want it to run there anyway -

**Comment by bherila** [comment]
Why does N2 not support TLS 1.2? You could just configure IIS accordingly. N2 does not have any requirement for an older TLS version.
