### ISSUE TITLE
Error "Could not find the type or name of the "Slideshow""

### ISSUE THREAD

**Issue by it19862** [n2cms/n2cms#824]
Win 7x64
VS 2015

1. Created a project ASP.NET Web application (C #)

2. Installed
Install-Package N2CMS.Dinamico
Install-Package N2CMS.Management
Install-Package N2CMS.Config.SQLite

3. Run debugging "F5"
4. I receive an error:
"Could not find the type or name of the namespace" Slideshow "(maybe there is no using directive or link to the assembly)"

How to fix the error?
![3146](https://user-images.githubusercontent.com/18245828/38606757-96379fc8-3d7f-11e8-9064-ba98bcdc5895.jpg)

**Comment by bherila** [comment]
Just delete the class and everything else should be working. Sorry about that.
