### ISSUE TITLE
Add button does not appear on parts with EditableChildren

### ISSUE THREAD

**Issue by bherila** [n2cms/n2cms#96]
n2 version 2.4.9.2

 I recently noticed that when you create a part and within that part you can add EditableChildren. 

 So far its fine but when you add more EditableChildrens the "Add" button does not show. I have marked the 
 EditableChildren on the image below. As you would see the "Links" button is missing.
![editableschildren](https://f.cloud.github.com/assets/1422004/354121/147f791a-a095-11e2-99e5-5cc42047b341.PNG)

Note that this problem occurs only the first time after adding an item with editable children part that in turn has editable children as a part. It can be worked around by performing a save and preview/publish. 

 This is however very confusing to our users who administer the actual content in N2. I do believe this is a recent regression as we haven't ran into this problem before.

**Comment by DKotoski** [comment]
I came across something similar as this on version 2.9.6.2.
When I try to add a part with editable children, when clicking to add a child there is exception shown and it fails.
If i add empty part i can save it and if i try to add children after it is created the exception is not shown and everything works fine.
